-- Migration 008 — Seed batch 2: ~30 new SaaS sources (field services, AI voice, e-commerce, creators, real estate, pets)

INSERT INTO saas_sources (name, slug, domain, tagline, description, logo_url, category, subcategory, mrr_reported, arr_reported, mrr_source, pricing_model, founder_names, founded_year, employee_count_range, tech_stack, platforms, source_urls, is_verified, is_featured)
VALUES

-- Field Service Management
('Jobber', 'jobber', 'getjobber.com',
 'Field service management for home service businesses',
 'All-in-one software for quoting, scheduling, invoicing and payment collection for home service businesses like landscaping, cleaning, and plumbing.',
 'https://logo.clearbit.com/getjobber.com',
 'scheduling', 'field-service', NULL, 45000000, 'Crunchbase',
 'subscription', 'Sam Pillar, Forrest Zeisler', 2011, '201-500',
 '["React","Ruby on Rails","PostgreSQL","AWS"]', '["web","mobile"]',
 '{"ph":"https://www.producthunt.com/products/jobber","g2":"https://www.g2.com/products/jobber/reviews"}',
 true, true),

('ServiceTitan', 'servicetitan', 'servicetitan.com',
 'The operating system for the trades',
 'Cloud-based software platform for residential and commercial field service companies in HVAC, plumbing, electrical and more.',
 'https://logo.clearbit.com/servicetitan.com',
 'scheduling', 'field-service', NULL, 600000000, 'Crunchbase',
 'subscription', 'Ara Mahdessian, Vahe Kuzoyan', 2012, '1001-5000',
 '["React","Java","AWS","PostgreSQL"]', '["web","mobile"]',
 '{"g2":"https://www.g2.com/products/servicetitan/reviews"}',
 true, true),

('Housecall Pro', 'housecall-pro', 'housecallpro.com',
 'Field service software for home service pros',
 'Mobile-first platform for plumbers, electricians, HVAC technicians and other home service businesses to manage their operations.',
 'https://logo.clearbit.com/housecallpro.com',
 'scheduling', 'field-service', NULL, 60000000, 'Crunchbase',
 'subscription', 'Ian Heidt', 2013, '201-500',
 '["React Native","Node.js","AWS"]', '["web","mobile"]',
 '{"ph":"https://www.producthunt.com/products/housecall-pro"}',
 true, false),

('Buildxact', 'buildxact', 'buildxact.com',
 'Construction estimating and project management software',
 'Job management software built specifically for small to medium builders and remodelers, with estimating, scheduling, client communication, and invoicing.',
 'https://logo.clearbit.com/buildxact.com',
 'biz-tool', 'construction', NULL, 8000000, 'Acquire.com',
 'subscription', NULL, 2010, '51-200',
 '["Angular","Node.js","AWS"]', '["web"]',
 '{"g2":"https://www.g2.com/products/buildxact/reviews"}',
 true, false),

-- Pet Industry
('Gingr', 'gingr', 'gingrapp.com',
 'Software for pet groomers, daycares, and boarding',
 'All-in-one pet care software for grooming salons, doggy daycares, boarding facilities, and training businesses.',
 'https://logo.clearbit.com/gingrapp.com',
 'scheduling', 'pet-care', NULL, 4000000, 'Acquire.com',
 'subscription', NULL, 2012, '11-50',
 '["Ruby on Rails","PostgreSQL"]', '["web","mobile"]',
 '{"g2":"https://www.g2.com/products/gingr/reviews"}',
 true, false),

('PetExec', 'petexec', 'petexec.net',
 'Web-based pet boarding and daycare software',
 'Cloud-based pet care software for groomers, boarders, daycare, and training facilities with online booking and automated reminders.',
 'https://logo.clearbit.com/petexec.net',
 'scheduling', 'pet-care', NULL, NULL, NULL,
 'subscription', NULL, 2007, '11-50',
 '["PHP","MySQL"]', '["web"]',
 '{}',
 true, false),

-- Fitness / Wellness
('Mangomint', 'mangomint', 'mangomint.com',
 'Modern salon and spa software',
 'Fast, simple, and beautiful salon and spa management software designed for teams of any size, with online booking and automated reminders.',
 'https://logo.clearbit.com/mangomint.com',
 'scheduling', 'beauty-wellness', NULL, 3000000, 'Indie Hackers',
 'subscription', NULL, 2018, '11-50',
 '["React","Node.js","Stripe"]', '["web"]',
 '{"ph":"https://www.producthunt.com/products/mangomint"}',
 true, false),

('Kicksite', 'kicksite', 'kicksite.com',
 'Martial arts school management software',
 'All-in-one management platform for martial arts schools with student tracking, billing, attendance, and belt promotion management.',
 'https://logo.clearbit.com/kicksite.com',
 'scheduling', 'fitness', NULL, NULL, NULL,
 'subscription', NULL, 2008, '11-50',
 '["PHP","MySQL"]', '["web"]',
 '{}',
 true, false),

('WellnessLiving', 'wellnessliving', 'wellnessliving.com',
 'Business management software for fitness and wellness',
 'All-in-one business management and marketing platform for fitness studios, spas, salons, and wellness businesses.',
 'https://logo.clearbit.com/wellnessliving.com',
 'scheduling', 'fitness', NULL, 20000000, 'Crunchbase',
 'subscription', 'Sasha Davydov, Len Fridman', 2012, '201-500',
 '["React","PHP","MySQL","AWS"]', '["web","mobile"]',
 '{"g2":"https://www.g2.com/products/wellnessliving/reviews"}',
 true, false),

-- AI Voice / Conversational AI
('Bland.ai', 'bland-ai', 'bland.ai',
 'AI phone calling platform for businesses',
 'Build, test, and deploy AI phone agents for sales, customer service, and operations at massive scale.',
 'https://logo.clearbit.com/bland.ai',
 'ai-agent', 'ai-voice', NULL, 3000000, 'Product Hunt',
 'usage', NULL, 2023, '11-50',
 '["Python","FastAPI","Twilio","AWS"]', '["web","api"]',
 '{"ph":"https://www.producthunt.com/products/bland-ai"}',
 true, true),

('Synthflow', 'synthflow', 'synthflow.ai',
 'No-code AI voice agent builder',
 'Create human-like AI phone agents without coding. Handle inbound and outbound calls for sales, support, and appointment booking.',
 'https://logo.clearbit.com/synthflow.ai',
 'ai-agent', 'ai-voice', NULL, 2000000, 'Product Hunt',
 'subscription', NULL, 2023, '11-50',
 '["React","Python","Twilio"]', '["web"]',
 '{"ph":"https://www.producthunt.com/products/synthflow"}',
 true, true),

-- AI Chatbots / Customer Support
('Chatbase', 'chatbase', 'chatbase.co',
 'Build an AI chatbot trained on your data',
 'Create custom ChatGPT-powered chatbots for your website using your documents and data, in minutes.',
 'https://logo.clearbit.com/chatbase.co',
 'ai-gen', 'chatbot', NULL, 1000000, 'Product Hunt',
 'subscription', 'Yasser Elsaid', 2023, '1-10',
 '["Next.js","Supabase","OpenAI"]', '["web"]',
 '{"ph":"https://www.producthunt.com/products/chatbase"}',
 true, true),

('Tidio', 'tidio', 'tidio.com',
 'Live chat and AI chatbot for e-commerce',
 'Customer communication platform with live chat, chatbots, and email marketing for small and medium businesses.',
 'https://logo.clearbit.com/tidio.com',
 'ai-gen', 'chatbot', NULL, 24000000, 'Crunchbase',
 'freemium', 'Tytus Golas, Przemyslaw Sadowski', 2013, '201-500',
 '["React","Node.js","WebSocket"]', '["web"]',
 '{"ph":"https://www.producthunt.com/products/tidio","g2":"https://www.g2.com/products/tidio/reviews"}',
 true, false),

-- E-commerce Tools
('Prisync', 'prisync', 'prisync.com',
 'Competitor price tracking for e-commerce',
 'Automated competitor price tracking and dynamic pricing software for e-commerce businesses to monitor prices and maximize margins.',
 'https://logo.clearbit.com/prisync.com',
 'automation', 'e-commerce', NULL, NULL, NULL,
 'subscription', NULL, 2013, '11-50',
 '["Python","Django","PostgreSQL"]', '["web"]',
 '{"g2":"https://www.g2.com/products/prisync/reviews"}',
 true, false),

('Metorik', 'metorik', 'metorik.com',
 'WooCommerce analytics and email automation',
 'Real-time reporting, analytics, and automated emails for WooCommerce stores, providing deep insights into customers and orders.',
 'https://logo.clearbit.com/metorik.com',
 'automation', 'e-commerce', NULL, NULL, 'Indie Hackers',
 'subscription', 'Bryce Adams', 2016, '1-10',
 '["Laravel","Vue.js","MySQL"]', '["web"]',
 '{"ph":"https://www.producthunt.com/products/metorik"}',
 true, false),

-- AI Content / Writing
('Jasper', 'jasper', 'jasper.ai',
 'AI copilot for marketing teams',
 'AI writing platform for enterprise marketing teams to create on-brand content across channels faster.',
 'https://logo.clearbit.com/jasper.ai',
 'ai-gen', 'copywriting', NULL, 125000000, 'Crunchbase',
 'subscription', 'Dave Rogenmoser, JP Morgan, Chris Hull', 2021, '201-500',
 '["React","Node.js","AWS","OpenAI"]', '["web"]',
 '{"ph":"https://www.producthunt.com/products/jasper","g2":"https://www.g2.com/products/jasper-ai/reviews"}',
 true, false),

('Copy.ai', 'copy-ai', 'copy.ai',
 'AI platform for marketing workflows',
 'Go-to-market AI platform that helps sales and marketing teams 10x their output with automated workflows and content generation.',
 'https://logo.clearbit.com/copy.ai',
 'ai-gen', 'copywriting', NULL, 18000000, 'Crunchbase',
 'freemium', 'Paul Yacoubian, Chris Lu', 2020, '51-200',
 '["React","Python","AWS","OpenAI"]', '["web"]',
 '{"ph":"https://www.producthunt.com/products/copy-ai","g2":"https://www.g2.com/products/copy-ai/reviews"}',
 true, false),

-- AI Presentations
('Gamma', 'gamma', 'gamma.app',
 'AI-powered presentations, docs and webpages',
 'A new medium for presenting ideas, powered by AI. Create beautiful presentations, documents, and webpages in minutes.',
 'https://logo.clearbit.com/gamma.app',
 'ai-gen', 'presentations', NULL, 15000000, 'Product Hunt',
 'freemium', 'Grant Lee, Jon Noronha, James Fox', 2020, '51-200',
 '["React","Node.js","AWS"]', '["web"]',
 '{"ph":"https://www.producthunt.com/products/gamma"}',
 true, true),

-- Real Estate
('Lofty', 'lofty', 'lofty.com',
 'AI-powered CRM for real estate agents',
 'All-in-one platform for real estate professionals with AI lead generation, CRM, marketing automation, and IDX website.',
 'https://logo.clearbit.com/lofty.com',
 'crm', 'real-estate', NULL, NULL, NULL,
 'subscription', NULL, 2016, '201-500',
 '["React","Java","AWS"]', '["web","mobile"]',
 '{"g2":"https://www.g2.com/products/lofty/reviews"}',
 true, false),

('Follow Up Boss', 'follow-up-boss', 'followupboss.com',
 'CRM for real estate teams',
 'Real estate CRM and lead management platform that centralizes leads from all sources and automates follow-up for agents and teams.',
 'https://logo.clearbit.com/followupboss.com',
 'crm', 'real-estate', NULL, 24000000, 'Crunchbase',
 'subscription', 'Dan Corkill, Tom Bosak', 2011, '51-200',
 '["React","PHP","MySQL"]', '["web","mobile"]',
 '{"g2":"https://www.g2.com/products/follow-up-boss/reviews"}',
 true, false),

-- Photography / Creators
('Studio Ninja', 'studio-ninja', 'studioninja.co',
 'CRM software for photographers',
 'All-in-one business management software for photographers with client management, contracts, invoices, questionnaires, and workflows.',
 'https://logo.clearbit.com/studioninja.co',
 'crm', 'photography', NULL, NULL, 'Indie Hackers',
 'subscription', 'Chris Morris', 2015, '1-10',
 '["Angular","Node.js","PostgreSQL"]', '["web"]',
 '{"ph":"https://www.producthunt.com/products/studio-ninja"}',
 true, false),

-- Invoice / Finance
('Invoice Ninja', 'invoice-ninja', 'invoiceninja.com',
 'Open-source invoicing for freelancers',
 'Free and open-source invoicing, expenses, time-tracking, and payments platform for freelancers and small businesses.',
 'https://logo.clearbit.com/invoiceninja.com',
 'invoicing', 'freelance', NULL, NULL, 'Indie Hackers',
 'freemium', 'Hillel Coren', 2014, '1-10',
 '["Laravel","Vue.js","MySQL"]', '["web","mobile","self-hosted"]',
 '{"ph":"https://www.producthunt.com/products/invoice-ninja","g2":"https://www.g2.com/products/invoice-ninja/reviews"}',
 true, false),

-- Marketing / SEO
('Rank Math', 'rank-math', 'rankmath.com',
 'WordPress SEO plugin',
 'The most powerful WordPress SEO plugin with AI-powered content optimization, rich snippets, schema markup, and rank tracking.',
 'https://logo.clearbit.com/rankmath.com',
 'marketing', 'seo', NULL, 12000000, 'Indie Hackers',
 'freemium', 'Bhanu Ahluwalia, Himanshu Ahluwalia', 2018, '51-200',
 '["PHP","React","MySQL"]', '["web"]',
 '{"ph":"https://www.producthunt.com/products/rank-math"}',
 true, false),

-- Automation / Operations
('Make', 'make', 'make.com',
 'Visual automation platform (formerly Integromat)',
 'No-code automation platform that connects apps and automates workflows visually, with advanced data manipulation capabilities.',
 'https://logo.clearbit.com/make.com',
 'automation', 'workflow', NULL, 100000000, 'Crunchbase',
 'freemium', NULL, 2012, '201-500',
 '["React","Node.js","PostgreSQL","AWS"]', '["web"]',
 '{"ph":"https://www.producthunt.com/products/make","g2":"https://www.g2.com/products/make/reviews"}',
 true, false),

('Cal.com', 'cal-com', 'cal.com',
 'Open-source scheduling infrastructure',
 'Open-source Calendly alternative with full customization, self-hosting option, team scheduling, and powerful integrations.',
 'https://logo.clearbit.com/cal.com',
 'scheduling', 'calendar', NULL, 5000000, 'Product Hunt',
 'freemium', 'Peer Richelsen, Bailey Pumfleet', 2021, '51-200',
 '["Next.js","tRPC","Prisma","PostgreSQL"]', '["web","api","self-hosted"]',
 '{"ph":"https://www.producthunt.com/products/cal-com","g2":"https://www.g2.com/products/cal-com/reviews"}',
 true, true),

-- Developer Tools
('Retool', 'retool', 'retool.com',
 'Low-code platform to build internal tools',
 'The fastest way to build internal tools. Connect to any database or API and build admin panels, dashboards, and CRUD apps.',
 'https://logo.clearbit.com/retool.com',
 'devtools', 'internal-tools', NULL, 120000000, 'Crunchbase',
 'freemium', 'David Hsu', 2017, '201-500',
 '["React","Node.js","PostgreSQL","AWS"]', '["web"]',
 '{"ph":"https://www.producthunt.com/products/retool","g2":"https://www.g2.com/products/retool/reviews"}',
 true, true),

('Raycast', 'raycast', 'raycast.com',
 'Supercharged productivity tool for Mac',
 'Blazingly fast, totally extendable launcher that lets you complete tasks, calculate, share common links, and much more.',
 'https://logo.clearbit.com/raycast.com',
 'productivity', 'launcher', NULL, 5000000, 'Product Hunt',
 'freemium', 'Thomas Paul Mann, Petr Nikolaev', 2020, '51-200',
 '["Swift","TypeScript","React"]', '["macos"]',
 '{"ph":"https://www.producthunt.com/products/raycast"}',
 true, false),

-- HR / Recruitment
('Greenhouse', 'greenhouse', 'greenhouse.com',
 'Applicant tracking and recruiting software',
 'Best-in-class hiring platform used by thousands of companies to optimize recruiting processes and make better hiring decisions.',
 'https://logo.clearbit.com/greenhouse.com',
 'hr', 'recruitment', NULL, 100000000, 'Crunchbase',
 'subscription', 'Daniel Chait, Jon Stross', 2012, '501-1000',
 '["Ruby on Rails","React","PostgreSQL","AWS"]', '["web"]',
 '{"g2":"https://www.g2.com/products/greenhouse/reviews"}',
 true, false),

-- Analytics
('Fathom Analytics', 'fathom-analytics', 'usefathom.com',
 'Simple, privacy-first website analytics',
 'A Google Analytics alternative that does not compromise on privacy and gives you website stats you actually need.',
 'https://logo.clearbit.com/usefathom.com',
 'devtools', 'analytics', NULL, 400000, 'Indie Hackers',
 'subscription', 'Jack Ellis, Paul Jarvis', 2018, '1-10',
 '["Go","Vue.js","MySQL"]', '["web"]',
 '{"ph":"https://www.producthunt.com/products/fathom-analytics"}',
 true, false),

('Plausible Analytics', 'plausible-analytics', 'plausible.io',
 'Lightweight, open-source web analytics',
 'Simple and privacy-friendly Google Analytics alternative with a clean dashboard, no cookies, and GDPR compliance built-in.',
 'https://logo.clearbit.com/plausible.io',
 'devtools', 'analytics', NULL, 1200000, 'Indie Hackers',
 'subscription', 'Uku Taht, Marko Saric', 2019, '1-10',
 '["Elixir","React","ClickHouse","PostgreSQL"]', '["web","self-hosted"]',
 '{"ph":"https://www.producthunt.com/products/plausible-analytics"}',
 true, false),

-- Education / Coaching
('Thinkific', 'thinkific', 'thinkific.com',
 'Online course platform for creators and businesses',
 'Platform for entrepreneurs and businesses to create, market, and sell online courses and communities.',
 'https://logo.clearbit.com/thinkific.com',
 'education', 'online-courses', NULL, 60000000, 'Crunchbase',
 'freemium', 'Greg Smith, Matt Smith, Miranda Lievers', 2012, '501-1000',
 '["Ruby on Rails","React","PostgreSQL","AWS"]', '["web"]',
 '{"ph":"https://www.producthunt.com/products/thinkific","g2":"https://www.g2.com/products/thinkific/reviews"}',
 true, false),

('Skool', 'skool', 'skool.com',
 'Community platform for creators and educators',
 'All-in-one platform to build paid communities, run online courses, and engage members with gamification and live events.',
 'https://logo.clearbit.com/skool.com',
 'education', 'community', NULL, 20000000, 'Product Hunt',
 'subscription', 'Sam Ovens', 2019, '11-50',
 '["React","Node.js","AWS"]', '["web","mobile"]',
 '{"ph":"https://www.producthunt.com/products/skool"}',
 true, true)

ON CONFLICT (slug) DO NOTHING;
